export const POLLS_LOADING = 'POLLS_LOADING';
export const POLLS_LOADING_SUCCEED = 'POLLS_LOADING_SUCCEED';
export const POLLS_LOADING_FAILED = 'POLLS_LOADING_FAILED';

export const POLL_UPDATING = 'POLL_UPDATING';
export const POLL_UPDATE_SUCCEED = 'POLL_UPDATE_SUCCEED';
export const POLL_UPDATE_FAILED = 'POLL_UPDATE_FAILED';

export const POLL_RESULTS_LOADING = 'POLL_RESULTS_LOADING';
export const POLL_RESULTS_LOADING_SUCCEED = 'POLL_RESULTS_LOADING_SUCCEED';
export const POLL_RESULTS_LOADING_FAILED = 'POLL_RESULTS_LOADING_FAILED';

export const VOTE_UPDATE = 'VOTE_UPDATE';
